#Here you can disable talents.
#Notice that players with admin privileges can bypass this.
[Talents]
	"doggytalents:guard_dog" = true
	"doggytalents:bed_finder" = true
	"doggytalents:black_pelt" = true
	"doggytalents:hunter_dog" = true
	"doggytalents:shock_absorber" = true
	"doggytalents:water_holder" = true
	"doggytalents:doggy_tools" = true
	"doggytalents:gate_passer" = true
	"doggytalents:flying_furball" = true
	"doggytalents:rescue_dog" = true
	"doggytalents:swimmer_dog" = true
	"doggytalents:ookamikaze" = true
	"doggytalents:puppy_eyes" = true
	"doggytalents:poison_fang" = true
	"doggytalents:chemi_canine" = true
	"doggytalents:quick_healer" = true
	"doggytalents:fire_drill" = true
	"doggytalents:sniffer_dog" = true
	"doggytalents:roaring_gale" = true
	"doggytalents:happy_eater" = true
	"doggytalents:pillow_paw" = true
	"doggytalents:fisher_dog" = true
	"doggytalents:doggy_dash" = true
	"doggytalents:doggy_armor" = true
	"doggytalents:pack_puppy" = true
	"doggytalents:creeper_sweeper" = true
	"doggytalents:pest_fighter" = true
	"doggytalents:mob_retriever" = true
	"doggytalents:hell_hound" = true
	"doggytalents:shepherd_dog" = true
	"doggytalents:wolf_mount" = true
	"doggytalents:doggy_torch" = true
